//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public string PreserveTime { get; set; }
        public string FoodAmount { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Assign { get; set; }
        public int ResId { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
